### ISSUE TITLE
Larger glitch dataset/generation issues

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/BBHNet#198] opened 2022-11-06 19:27 UTC
@EthanMarx what's the status of some of the issues we're seeing with omicron? If/when those get resolved, how large of glitch datasets will we be working with, and what are the easiest strategies for growing those?

**Comment by EthanMarx** [comment] 2022-11-07 15:05
The issue appears to be resolved by upgrading to the latest omicron version (3.2.0, that is now stable). I would like both you and Will to run with this new environment so we can cross check results. I'm seeing ~ 700 glitches for each IFO during the training period. 

A few ideas for generating larger glitch datasets:

1. We currently restrict all of our analysis to coincident times, and thus don't take advantage of times where only 1 IFO is online. It might be useful to think of a strategy to incorporate glitches from these times as well. 
2. Implement some bootstrapping method where we incorporate events our network performed poorly on back into the glitch dataset. 
3. Increase the length of our training period

These are the only ways I can think of to get more "natural" glitches. 

I think the major problem with our glitch dataset is a lack of high SNR glitches. One thing that would be super interesting would be to do some sort of SNR re-weighting with glitches. The problem here is we would need a method to extract the glitch from the background, otherwise we would be raising the noise floor as well. We could also think about sampling the glitches we currently have from some SNR distribution, so the network sees the louder glitches more often.

**Comment by alecgunny** [comment] 2022-11-07 18:30
Ran this morning with the newer version of omicron and am seeing 195 Hanford glitches and 751 Livingston glitches.

Would it make sense to pull from periods before the training period for glitches? Most of the reason we keep the training period relatively short is so that we can keep all the data in memory at once. We'll probably eventually relax this constraint, but until then we should be free to pull glitches from any time we want before the test period right?

**Comment by EthanMarx** [comment] 2022-11-07 18:40
This makes a lot of sense. In an online scenario we'd have access to those glitches anyways, so I don't see why not.

**Comment by EthanMarx** [comment] 2022-12-28 15:06
I think I've finally figured out the issue here, and for the moment it might be out of our control. 

To summarize the problem we were seeing:

1. Omicron jobs would randomly fail due to some error loading the frame cache file.
2. Which jobs failed was more or less random: 2 different workflow runs might have different jobs failing, or no jobs failing at all. 

In addition to the condor dag file, pyomicron creates a bash script that contains all the same jobs. When running this script, the jobs would consistently complete without failure. The major difference between running via condor and simply running the bash script is that the bash script jobs are run serially, while the condor jobs are launched in parallel. 

What i noticed was that when run serially, there was a unique frame cache file created for each job. When run in parallel via condor, jobs would sometimes share the same frame cache file. I tracked down the naming convention for the frame cache files and found it is a random number generator seeded by the current time. 

This all leads me to believe that the problem is some race condition between jobs that share the same frame cache file. 
I've notified the main omicron developer and suggested he combines the time with some process specific value to the seed initializer. 

Since this is an omicron (as opposed to pyomicron) issue, there is not much we can do directly to fix it. In the mean time what we can do as a hacky work around is to run the bash script created by pyomicron directly. This doesn't fit well into the automation scheme, but I think this is the best we can do for the time being.

**Comment by alecgunny** [comment] 2022-12-28 18:53
Really really awesome digging, even if the resolution is less than ideal. With what level of resolution is the current time used to generate the RNG seed, just to the second?

**Comment by EthanMarx** [comment] 2022-12-28 19:08
Yeah to the second

**Comment by alecgunny** [comment] 2023-02-07 05:19
Re-upping this for publication and to update with latest status:
- Ethan has gotten issues resolved on the Omicron side, but we need to wait for the fixes to make it into a public release
- Short term solution is to build Omicron from source with latest changes then use this to construct a large glitch dataset and distribute it internally to be picked up via caching

**Comment by EthanMarx** [comment] 2023-02-07 22:06
Gonna close this: short term solution has been resolved, and it actually looks like omicron 4.0.0 is released (at least on git.ligo.org, will have to wait for cond-forge push)

**Closed by EthanMarx** 2023-02-07 22:06 UTC
Labels: question, optimization
